import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSelector, useDispatch } from "react-redux";
import { example } from "../store/user/userSlice";
import { exampleSelector } from "../store/user/userSelectors";
import { Column } from "../components/Layout/Column/ColumnAtom";
import { Row } from "../components/Layout/Row/RowAtom";
import { ContainerFluid } from "../components/Layout/Container/ContainerAtom";

export default function Home() {
  const { valueExample } = useSelector(exampleSelector);
  const dispatch = useDispatch();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ContainerFluid>
          <Row>
            <Column size={12} md={6} lg={3}>
              <h1>ASD</h1>
            </Column>
          </Row>
        </ContainerFluid>
        <a onClick={() => dispatch(example())} className={styles.card}>
          <h2>REDUX TEST {valueExample}</h2>
        </a>
      </main>
    </div>
  );
}
